// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Park.Models;

namespace Park.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20200131204931_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Park.Models.PublicPark", b =>
                {
                    b.Property<int>("PublicParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("PublicParkId");

                    b.ToTable("PublicParks");

                    b.HasData(
                        new
                        {
                            PublicParkId = 1,
                            City = "Bar Harbor",
                            Name = "Acadia",
                            State = "Maine"
                        },
                        new
                        {
                            PublicParkId = 2,
                            City = "Moab",
                            Name = "Arches",
                            State = "Utah"
                        },
                        new
                        {
                            PublicParkId = 3,
                            City = "Rapid City",
                            Name = "Badlands",
                            State = "Soulth Dakoda"
                        },
                        new
                        {
                            PublicParkId = 4,
                            City = "Alpine",
                            Name = "Big Bend",
                            State = "Texas"
                        },
                        new
                        {
                            PublicParkId = 5,
                            City = "Klamath Falls",
                            Name = "Crater Lake",
                            State = "Oregon"
                        },
                        new
                        {
                            PublicParkId = 6,
                            City = "Lone Pine",
                            Name = "Death Valley",
                            State = "Nevada"
                        },
                        new
                        {
                            PublicParkId = 7,
                            City = "Healy",
                            Name = "Denali",
                            State = "Alaska"
                        },
                        new
                        {
                            PublicParkId = 8,
                            City = "Coconino",
                            Name = "Grand Canyon",
                            State = "Arizona"
                        },
                        new
                        {
                            PublicParkId = 9,
                            City = "Montezuma",
                            Name = "Mesa Verde",
                            State = "Colorado"
                        },
                        new
                        {
                            PublicParkId = 10,
                            City = "Tacoma",
                            Name = "Mount Rainier",
                            State = "Washington"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
